/* 
**  mod_fastdfs.c -- Apache sample fastdfs module
**  [Autogenerated via ``apxs -n fastdfs -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_fastdfs.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /fastdfs in as follows:
**
**    #   httpd.conf
**    LoadModule fastdfs_module modules/mod_fastdfs.so
**    <Location /fastdfs>
**    SetHandler fastdfs
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /fastdfs and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/fastdfs 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_fastdfs.c
*/ 

#include <unistd.h>
#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_request.h"
#include "ap_config.h"
#include "http_core.h"
#include "common.c"

void fdfs_output_headers(void *arg, struct fdfs_http_response *pResponse)
{
	request_rec *r;

	if (pResponse->header_outputed)
	{
		return;
	}

	pResponse->header_outputed = true;

	r = (request_rec *)arg;
	r->status = pResponse->status;

	if (pResponse->status != HTTP_OK
	 && pResponse->status != HTTP_PARTIAL_CONTENT)
	{
		if (pResponse->status == HTTP_MOVETEMP)
		{
			if (pResponse->range_len > 0)
			{
				apr_table_setn(r->headers_out, "Range", \
					pResponse->range);
			}
			apr_table_setn(r->headers_out, "Location", \
				pResponse->redirect_url);
		}

		return;
	}

	if (pResponse->content_type != NULL)
	{
		r->content_type = pResponse->content_type;
	}
	ap_set_content_length(r, pResponse->content_length);

	if (pResponse->attachment_filename != NULL)
	{
		snprintf(pResponse->content_disposition, \
			sizeof(pResponse->content_disposition), \
			"attachment; filename=\"%s\"", \
			pResponse->attachment_filename);
		apr_table_setn(r->headers_out, "Content-Disposition", \
				pResponse->content_disposition);
	}

	apr_table_setn(r->headers_out, "Last-Modified", \
			pResponse->last_modified_buff);

	apr_table_setn(r->headers_out, "Accept-Ranges", "bytes");
	if (pResponse->content_range_len > 0)
	{
		apr_table_setn(r->headers_out, "Content-Range", \
				pResponse->content_range);
	}
}

int fdfs_send_reply_chunk(void *arg, const bool last_buff, \
		const char *buff, const int size)
{
	int remain_bytes;
	int bytes_send;

	remain_bytes = size;
	while (remain_bytes > 0)
	{
		bytes_send = ap_rwrite(buff + (size - remain_bytes), \
					remain_bytes, (request_rec *)arg);
		if (bytes_send <= 0)
		{
			return EIO;
		}

		remain_bytes -= bytes_send;
	}

	return 0;
}

static int fastdfs_handler(request_rec *r)
{
	struct fdfs_http_context context;
	const char *if_modified_since;
	const char *range;

	if (strcmp(r->handler, "fastdfs")) {
		return DECLINED;
	}

	memset(&context, 0, sizeof(context));
	context.arg = r;
	context.header_only = r->header_only;
	context.url = r->unparsed_uri;
	context.output_headers = fdfs_output_headers;
	context.send_reply_chunk = fdfs_send_reply_chunk;
	//context.send_file = NULL;
	//context.proxy_handler = NULL;
	context.server_port = r->connection->local_addr->port;

	if_modified_since = apr_table_get(r->headers_in, "If-Modified-Since");
	if (if_modified_since != NULL)
	{
		int len;
		len = strlen(if_modified_since);
		if (len < sizeof(context.if_modified_since))
		{
			memcpy(context.if_modified_since, \
				if_modified_since, len);
		}
	}

	range = apr_table_get(r->headers_in, "Range");
	if (range != NULL)
	{
		if (fdfs_parse_range(range, &(context.range)) != 0)
		{
			logError("file: "__FILE__", line: %d, " \
				"bad request, invalid range: %s", \
				__LINE__, range);
			return DECLINED;
		}
		context.if_range = true;
	}

	fdfs_http_request_handler(&context);

	return OK;
}

static void fastdfs_register_hooks(apr_pool_t *p)
{
	static int loaded = 0;
	int result;

	if (!loaded)
	{
		loaded = 1;
		if ((result=fdfs_mod_init()) != 0)
		{
			exit(result);
		}
	}

	ap_hook_handler(fastdfs_handler, NULL, NULL, APR_HOOK_MIDDLE);

	/*
	//fprintf(stderr, "register hooks, loaded=%d, p=%x, pid=%d, ppid=%d, " \
		tracker server count: %d\n\n", loaded, p, getpid(), getppid(), \
		g_tracker_group.server_count);
	*/
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA fastdfs_module = {
	STANDARD20_MODULE_STUFF, 
	NULL,                  /* create per-dir    config structures */
	NULL,                  /* merge  per-dir    config structures */
	NULL,                  /* create per-server config structures */
	NULL,                  /* merge  per-server config structures */
	NULL,                  /* table of config file commands       */
	fastdfs_register_hooks  /* register hooks                      */
};

